### ISSUE TITLE
能否提供个部署文档？

### ISSUE THREAD

**Issue by ztl198573** [liuhll/silky.hero#3]
装好redis, nacos, rabittmq, mysql 配置好之后 
直接用VS启动网关时
执行这里 endpoints.MapSilkyRpcServices();
报异常： Silky.Core.Exceptions.SilkyException:“RpcEndpoint does not exist”

**Comment by liuhll** [comment]
你好,你获取的是最新的代码吗?

**Comment by liuhll** [comment]
你获取最新的代码 这个有可能是因为silky版本不是最新的版本 所以出现这个bug

**Comment by ztl198573** [comment]
包信息如下：![image](https://user-images.githubusercontent.com/5326661/197089957-4578a7cb-0855-4461-8e42-c5a57e893c8a.png)
Bug依然如此 Silky.Core.Exceptions.SilkyException:“RpcEndpoint does not exist”
![image](https://user-images.githubusercontent.com/5326661/197090040-647b4633-8798-486d-967e-1d253868411a.png)
怀疑RPC 未能正确启动

配置文件如下
appsettings.yaml
serilog:
  minimumLevel:
    default: Information
    override:
      Microsoft: Warning
      Microsoft.Hosting.Lifetime: Information
      Silky: Debug
  writeTo:
    - name: File
      args:
        path: "./logs/log-.log"
        rollingInterval: Day
    - name: Console
      args:
        outputTemplate: "[{Timestamp:yyyy/MM/dd HH:mm:ss} {Level:u11}] {Message:lj} {NewLine}{Exception}{NewLine}"
        theme: "Serilog.Sinks.SystemConsole.Themes.SystemConsoleTheme::Literate, Serilog.Sinks.Console"
healthChecksUI:
  healthChecks:
    - name: rpc
      uri: http://127.0.0.1:6000/silkyrpc/healthz
    - name: gateway
      uri: http://127.0.0.1:6000/silkygateway/healthz
  evaluationTimeinSeconds: 30
  minimumSecondsBetweenFailureNotifications: 60
dashboard:
  tenantNameFiledName: tenantName
  userNameFiledName: account
  passwordFiledName: password
skyWalking:
  serviceName: Silky.GatewayHost
  headerVersions:
    - sw8
  sampling:
    samplePer3Secs: -1
    percentage: -1.0
  logging:
    level: Debug
    filePath: "logs/skyapm-{Date}.log"
  transport:
    interval: 3000
    protocolVersion: v8
    queueSize: 30000
    batchSize: 3000
    gRPC:
      servers: "127.0.0.1:11800"
      timeout: 10000
      connectTimeout: 10000
      reportTimeout: 600000

appsettings.Production.yaml
rpc:
  token: ypjdYOzNd4FwENJiEARMLWwK0v7QUHPW
registrycenter:
  type: Nacos
  namespace: ztl
  serverAddresses:
    - http://10.0.0.129:8848/
  userName: nacos
  password: nacos
  groupName: DEFAULT_GROUP
  clusterName: DEFAULT
  registerEnabled: true
  instanceEnabled: true
  namingUseRpc: true
distributedCache:
  redis:
    isEnabled: true
    configuration: 10.0.0.129:6379,defaultDatabase=0
gateway:
  jwtSecret: jv1PZkwjLVCEygM7faLLvEhDGWmFqRUW

appsettings.Development.yaml
rpc:
  token: ypjdYOzNd4FwENJiEARMLWwK0v7QUHPW

governance:
  timeoutMillSeconds: 0
registrycenter:
  type: Nacos
  namespace: ztl
  serverAddresses:
    - http://10.0.0.129:8848/
  userName: nacos
  password: nacos
  groupName: DEFAULT_GROUP
  clusterName: DEFAULT
  registerEnabled: true
  instanceEnabled: true
  namingUseRpc: true
distributedCache:
  redis:
    isEnabled: true
    configuration: 10.0.0.129:6379,defaultDatabase=0
rabbitMq:
  host: 10.0.0.129
  port: 5672
  userName: admin
  password: admin
  virtualHost: /
gateway:
  jwtSecret: jv1PZkwjLVCEygM7faLLvEhDGWmFqRUW

redis  nacos  rabbitmq 都在 10.0.0.129 上， 并正确运行

**Comment by liuhll** [comment]
我自己开发很少使用nocas作为服务注册中心,这个是我之前使用Nocas作为服务注册中心的配置,你可以看一下


```yaml
registrycenter:
  type: Nacos
  namespace: public
  serverAddresses:
    - http://127.0.0.1:8848/
    - http://127.0.0.1:8849/
    - http://127.0.0.1:8850/
  userName: nacos
  password: nacos
  groupName: DEFAULT_GROUP
  clusterName: DEFAULT
  registerEnabled: true
  instanceEnabled: true
  namingUseRpc: true
```

你检查一下你的配置是否正确,或者你可以先把服务注册中心设置为`Zookeeper`或是`Consul`,我这边也试试使用`Nocas`作为服务注册中心是不是有这个问题

**Comment by liuhll** [comment]
你 Nocas配置的名称空间`namespace: ztl`是不是不存在?

**Comment by liuhll** [comment]
我看了源码 貌似这个异常跟服务注册类型无关,你加我微信:bea084100123  我帮你看看吧

**Comment by liuhll** [comment]
审级到最新版本即可
